development: &default
  adapter: postgresql
  database: paperclip_demo_development
  encoding: utf8
  min_messages: warning
  pool: 5
  reaping_frequency: 10
  timeout: 5000

test:
  <<: *default
  database: paperclip_demo_test

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>
